{
  "questionText": "Как можно обработать ошибку, возникшую внутри обещания (Promise) в JavaScript?",
  "type": "checkbox",
  "answers": [
    {
      "text": "Используя метод `catch()` на объекте `Promise`",
      "isCorrect": true
    },
    {
      "text": "Используя метод `then()` с двумя аргументами - функциями для обработки успешного и неуспешного выполнения",
      "isCorrect": true
    },
    {
      "text": "Используя метод `finally()` на объекте `Promise`",
      "isCorrect": true
    },
    {
      "text": "Используя оператор `try-catch` внутри функции, возвращающей объект `Promise`",
      "isCorrect": true
    }
  ],
  "descriptionMarkup": "В JavaScript можно обрабатывать ошибки, возникшие внутри обещания (Promise) с помощью метода `catch()` на объекте `Promise`, использования метода then() с двумя аргументами - функциями для обработки успешного и неуспешного выполнения, использования метода `finally()` на объекте `Promise`, или использования оператора `try-catch` внутри функции, возвращающей объект `Promise`"
}
